# This workflow will do a clean installation of node dependencies, cache/restore them,
# build the source code, and run tests across different versions of node.

name: Node.js CI

on:
  push:
    branches: [ "master" ]

jobs:
  build:
    runs-on: self-hosted

    strategy:
      matrix:
        node-version: [18.x]

    steps:
    - uses: actions/checkout@v4

    - name: Debug - List files
      run: ls -la

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'pnpm'

    - name: Install pnpm globally
      run: npm install -g pnpm

    - name: Install dependencies
      run: pnpm install --frozen-lockfile
     
    - name: Install PM2 globally
      run: pnpm install -g pm2

    - name: Restart backend with PM2
      run: pm2 restart Backend || pm2 start server.js --name Backend
