name: Node.js CI

on:
  push:
    branches: [ "master" ]

jobs:
  build:
    runs-on: self-hosted

    strategy:
      matrix:
        node-version: [18.x]

    steps:
    - uses: actions/checkout@v4
      name: Checkout repository

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'

    - name: Install dependencies
      run: npm ci
      working-directory: /home/ubuntu/actions-runner/_work/awsdemo-Nodejs/awsdemo-Nodejs

    - name: Restart PM2
      run: pm2 restart Backend
      working-directory: /home/ubuntu/actions-runner/_work/awsdemo-Nodejs/awsdemo-Nodejs
